### ISSUE TITLE
Unipept 2.0 release checklist

### ISSUE THREAD

**Issue by bmesuere** [unipept/unipept#162]
- [x] Add unique peptide finder body copy to home page (#160)
- [x] Add full 2.0 changelog news post
- [x] Add summary 2.0 news post
- [x] Dump the sherlock database and back it up
- [x] Load the sherlock database into scruffy
- [x] Update the server and reboot everything
- [x] Put server in production mode and test the worker js file
- [x] Disable access Toon
- [x] Test in all browsers
- [x] Merge develop branch into master and deploy
- [x] Request cname change for unipept.ugent.be
- [x] Add tag to google analytics
- [x] Email Allesandro and Carolin to report the sunburst issue is fixed

_[Original issue](https://github.ugent.be/unipept/unipept/issues/162) by @bmesuere on Wed Oct 16 2013 at 20:57._
_Closed by @bmesuere on Fri Nov 01 2013 at 12:41._

**Comment by bmesuere** [comment]
there seem to be some cache issues


_[Original comment](https://github.ugent.be/unipept/unipept/issues/162#issuecomment-6595) by @bmesuere on Mon Oct 28 2013 at 09:46._

**Comment by bmesuere** [comment]
fixed!


_[Original comment](https://github.ugent.be/unipept/unipept/issues/162#issuecomment-6598) by @bmesuere on Mon Oct 28 2013 at 10:37._
