### ISSUE TITLE
2.1 release checklist

### ISSUE THREAD

**Issue by bmesuere** [unipept/unipept#175]
- [x] Check if bootstrap 3 fonts work in production mode
- [x] Enable svg gzip compression in apache
- [x] Test in all browsers (respond.js in IE?, html5 in IE?, svg embeds?)
- [x] Merge develop branch into master and deploy
- [x] Deploy
- [x] Add 2.1 changelog news post
- [x] Change old 2.0 changelog
- [x] Add tag to google analytics

_[Original issue](https://github.ugent.be/unipept/unipept/issues/175) by @bmesuere on Mon Oct 28 2013 at 14:08._
_Closed by @bmesuere on Mon Dec 23 2013 at 15:20._

**Comment by bmesuere** [comment]
2.0 changelog

``` html
Unipept 2.0 includes these updates:
<dl class="dl-horizontal changelog">
<dt><span class="label label-success">added</span></dt><dd>The Unique Peptide Finder</dd>
<dt><span class="label label-success">added</span></dt><dd>GO and EC cross references to database</dd>
<dt><span class="label label-success">added</span></dt><dd>Search settings to the batch run script</dd>
<dt><span class="label label-success">added</span></dt><dd>A timeout before filtering the tree on the multi result page</dd>
<dt><span class="label label-success">added</span></dt><dd>Invalidation "metagenome" NCBI taxa</dd>
<dt><span class="label label-primary">improved</span></dt><dd>Tweaked the lineage invalidation</dd>
<dt><span class="label label-primary">improved</span></dt><dd>Code spring cleaning and rewrite of backend scripts</dd>
<dt><span class="label label-primary">improved</span></dt><dd>Switch from JS animations to CSS animations where possible</dd>
<dt><span class="label label-danger">fixed</span></dt><dd>A bug when attempting to load a pride dataset without entering an id</dd>
<dt><span class="label label-danger">fixed</span></dt><dd>A bug where only 1 number was shown in the tree on the multi result page</dd>
<dt><span class="label label-danger">fixed</span></dt><dd>A bug where the sizes of the slices in the sunburst were not correct</dd>
<dt><span class="label label-danger">fixed</span></dt><dd>A bug where downloading results from results page didn't behave as expected</dd>
<dt><span class="label label-info">updated</span></dt><dd>Uniprot to 2013.04</dd>
<dt><span class="label label-info">updated</span></dt><dd>Bootstrap to 2.3.1</dd>
<dt><span class="label label-info">updated</span></dt><dd>Rails to 3.2.13</dd>
<dt><span class="label label-info">updated</span></dt><dd>D3.js to 3.3.8</dd>
<dt><span class="label label-info">updated</span></dt><dd>html2canvas to 2013.04</dd>
</dl>
```


_[Original comment](https://github.ugent.be/unipept/unipept/issues/175#issuecomment-6638) by @bmesuere on Fri Nov 01 2013 at 22:18._

**Comment by bmesuere** [comment]
2.1 changelog

``` html
Unipept 2.1 includes these updates:
<dl class="dl-horizontal changelog">
<dt><span class="label label-success">added</span></dt><dd>A fresh coat of paint for most of the pages</dd>
<dt><span class="label label-success">added</span></dt><dd>Support for high resolution (retina) displays in all images and icons</dd>
<dt><span class="label label-success">added</span></dt><dd>An option to download the data in the unique peptide graph as a Microsoft Excel compatible CSV file</dd>
<dt><span class="label label-success">added</span></dt><dd>An option to download the sunburst and unique peptide graph as an SVG file</dd>
<dt><span class="label label-primary">improved</span></dt><dd>Rewrite of all file download code to improve the user experience</dd>
<dt><span class="label label-primary">improved</span></dt><dd>Smoother dragging in the unique peptide graph</dd>
<dt><span class="label label-primary">improved</span></dt><dd>Custom taxonomy tree implementation on the multi-peptide result page</dd>
<dt><span class="label label-danger">fixed</span></dt><dd>A bug where the download button stayed disabled after downloading the results on the multi-peptide page</dd>
<dt><span class="label label-danger">fixed</span></dt><dd>A bug with full screen mode on the unique peptide page</dd>
<dt><span class="label label-danger">fixed</span></dt><dd>A bug where dragging a node triggered a popover in some browsers</dd>
<dt><span class="label label-info">updated</span></dt><dd>Bootstrap to 3.0.3</dd>
<dt><span class="label label-info">updated</span></dt><dd>D3.js to 3.3.10</dd>
</dl>
```


_[Original comment](https://github.ugent.be/unipept/unipept/issues/175#issuecomment-7216) by @bmesuere on Fri Dec 20 2013 at 17:24._
