### ISSUE TITLE
2.2 release checklist

### ISSUE THREAD

**Issue by bmesuere** [unipept/unipept#210]
- [x] Add planned downtime message to the production website
- [x] Test in all browsers
- [x] Create new release, update version in footer and push master
- [x] Add Github release
- [x] apt-get update and upgrade
- [x] Install Ruby 2.1
- [x] Install sendmail
- [x] Update the database
- [x] Deploy
- [x] Add 2.2 + changelog news post
- [x] Add tag to google analytics
- [x] Create public branch based on master
- [x] Delete 2.2 feature branches
- [x] Publish code in github.com #354
- [x] Email Alessandro about the fixed colors
- [x] Email Simon about the IL issue

_[Original issue](https://github.ugent.be/unipept/unipept/issues/210) by @bmesuere on Mon Dec 23 2013 at 15:26._
_Closed by @bmesuere on Sat Jun 07 2014 at 16:28._

**Comment by bmesuere** [comment]
Install ruby 2.1:

```
sudo apt-get remove ruby1.9
curl -L https://get.rvm.io | bash -s stable
rvm install 2.1
gem install passenger
passenger-install-apache2-module
```


_[Original comment](https://github.ugent.be/unipept/unipept/issues/210#issuecomment-9149) by @bmesuere on Sat May 03 2014 at 16:53._

**Comment by bmesuere** [comment]
Database update statements:

``` sql
CREATE TABLE IF NOT EXISTS `unipept`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(8) NOT NULL,
  `admin` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;
```

``` sql
INSERT INTO `unipept`.`users` (`id`, `username`, `admin`) VALUES (1, 'bmesuere', 1);
INSERT INTO `unipept`.`users` (`id`, `username`, `admin`) VALUES (2, 'pdawyndt', 1);
INSERT INTO `unipept`.`users` (`id`, `username`, `admin`) VALUES (3, 'guest', 0);
```

``` sql
INSERT INTO `unipept`.`lineages` (`taxon_id`) VALUES (1);
```


_[Original comment](https://github.ugent.be/unipept/unipept/issues/210#issuecomment-9990) by @bmesuere on Tue Jun 03 2014 at 22:47._

**Comment by bmesuere** [comment]
changelog message:

``` html
Unipept 2.2 includes these updates:
<dl class="dl-horizontal changelog">
<dt><span class="label label-success">added</span></dt><dd>Peptidome clustering</dd>
<dt><span class="label label-success">added</span></dt><dd>myGenomes to peptidome analysis</dd>
<dt><span class="label label-success">added</span></dt><dd>Fixed color option to the sunburst graph</dd>
<dt><span class="label label-success">added</span></dt><dd>The option to disable individual lines in the unique peptide finder</dd>
<dt><span class="label label-success">added</span></dt><dd>Full screen support for Internet Explorer 11</dd>
<dt><span class="label label-success">added</span></dt><dd>Links to the bioproject pages where appropriate</dd>
<dt><span class="label label-success">added</span></dt><dd>Invalidation "metagenome" NCBI taxa</dd>
<dt><span class="label label-primary">improved</span></dt><dd>The design of the unique peptide finder: abbreviations for organisms names, use icons where possible, better help texts, ...</dd>
<dt><span class="label label-primary">improved</span></dt><dd>The loading of the unique sequences in the unique peptide finder</dd>
<dt><span class="label label-danger">fixed</span></dt><dd>A bug where the genome size was not shown by default</dd>
<dt><span class="label label-danger">fixed</span></dt><dd>A bug causing the LCA to be root in some cases in the unique peptide finder</dd>
<dt><span class="label label-danger">fixed</span></dt><dd>A bug where matching children weren't shown while filtering on the multi-peptide results page</dd>
<dt><span class="label label-danger">fixed</span></dt><dd>A bug where the custom drag cursors weren't shown in Internet Explorer</dd>
<dt><span class="label label-danger">fixed</span></dt><dd>A crash when using autosort without genomes</dd>
<dt><span class="label label-danger">fixed</span></dt><dd>An issue with the full screen view of the peptide finder graph</dd>
<dt><span class="label label-danger">fixed</span></dt><dd>An issue where the download dialog didn't disappear by pressing the escape key</dd>
<dt><span class="label label-info">updated</span></dt><dd>Rails to 4.1.1</dd>
<dt><span class="label label-info">updated</span></dt><dd>Ruby to 2.1</dd>
<dt><span class="label label-info">updated</span></dt><dd>Bootstrap to 3.1.1</dd>
<dt><span class="label label-info">updated</span></dt><dd>D3.js to 3.4.6</dd>
</dl>
```


_[Original comment](https://github.ugent.be/unipept/unipept/issues/210#issuecomment-9998) by @bmesuere on Wed Jun 04 2014 at 21:07._

**Comment by bmesuere** [comment]
There were some serious issues when trying to deploy to production:
- The capistrano assets precompilation failed.
  -> I created a custom recipe to do the precompilation
- This created new issues with the bootstrap icon fonts: apparently rails 4 doesn't precompile assets with all filetypes anymore.
  -> I added these filetypes to the list of assets to compile
- This showed there were also issues with other assets: rails 4 stopped generating assets without digest in the filename. This caused the workers and fonts to 404.
  -> I created a custom rake task to copy these files to the assets directory
- I figured out the initial capistrano problem was due to the roles being parsed incorrectly (strings were not converted to symbols.
  -> I fixed this and disabled my custom recipe
- The default assets precompilation generated the assets in an incorrect location causing everything to fail again
  -> I again disabled the default precompilation and used my recipe

After almost 10 hours of debugging, everything seems to work now.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/210#issuecomment-10023) by @bmesuere on Sat Jun 07 2014 at 16:09._
