### ISSUE TITLE
2.3 release checklist

### ISSUE THREAD

**Issue by bmesuere** [unipept/unipept#363]
- [x] Update version numbers
- [x] Update readme.md
- [x] Add planned downtime message to the production website
- [x] Put scruffy in production mode and test the production deployment
- [x] Test in all browsers
- [x] Create new release, update version in footer and push master
- [x] Add Github release
- [x] apt-get update and upgrade
- [x] Deploy
- [x] Add 2.3 + changelog news post
- [x] Add tag to google analytics
- [x] Create public branch and push to github.com
- [x] Delete 2.3 feature branches

_[Original issue](https://github.ugent.be/unipept/unipept/issues/363) by @bmesuere on Sat Jun 07 2014 at 16:30._
_Closed by @bmesuere on Sat Aug 02 2014 at 18:48._
