### ISSUE TITLE
2.4 release checklist

### ISSUE THREAD

**Issue by bmesuere** [unipept/unipept#391]
- [x] Add planned downtime message to the production website
- [x] Update readme.md
- [x] Put scruffy in production mode and test the production deployment
- [x] Test in all browsers
- [x] Create new release, update version numbers and push master
- [x] Add Github release
- [x] apt-get update and upgrade
- [x] update the database
- [x] Deploy
- [x] Test if hidden internal nodes work
- [x] Add 2.4 + changelog news post
- [x] Add tag to google analytics
- [x] Create public branch and push to github.com
- [x] Delete 2.4 feature branches

_[Original issue](https://github.ugent.be/unipept/unipept/issues/391) by @bmesuere on Sat Aug 02 2014 at 19:07._
_Closed by @bmesuere on Tue Oct 07 2014 at 17:23._

**Comment by bmesuere** [comment]
``` mysql
DROP TABLE `unipept`.`counters`;
```


_[Original comment](https://github.ugent.be/unipept/unipept/issues/391#issuecomment-10377) by @bmesuere on Tue Aug 05 2014 at 14:23._

**Comment by bmesuere** [comment]
``` html
Unipept 2.4 consists of 438 commits and 206 changed files with 9,015 additions and 4,048 deletions. This includes these updates:
<dl class="dl-horizontal changelog">
<dt><span class="label label-success">added</span></dt><dd>An <span class="initialism">API</span> and documentation</dd>
<dt><span class="label label-success">added</span></dt><dd>A reset button to the visualizations of the metaproteomics analysis results</dd>
<dt><span class="label label-success">added</span></dt><dd>A new treeview visualization to the tryptic peptide analysis results</dd>
<dt><span class="label label-primary">improved</span></dt><dd>The organisation of the tryptic peptide analysis page</dd>
<dt><span class="label label-primary">improved</span></dt><dd>The export of the hpylogenetic tree by hiding the internal nodes on export</dd>
<dt><span class="label label-danger">fixed</span></dt><dd>The database to account for bigger uniprot accession numbers</dd>
<dt><span class="label label-danger">fixed</span></dt><dd>The database to account for bigger EMBL and Refseq cross references</dd>
<dt><span class="label label-info">updated</span></dt><dd>Ruby on Rails to 4.1.4</dd>
<dt><span class="label label-info">updated</span></dt><dd>D3.js to 3.4.11</dd>
</dl>
The single peptide analysis was renamed to tryptic peptide analysis and multi peptide analysis was renamed to metaproteomics analysis.
<br>
Known issues: the list of GO terms was disabled because it's missing from the database.
```


_[Original comment](https://github.ugent.be/unipept/unipept/issues/391#issuecomment-11293) by @bmesuere on Tue Oct 07 2014 at 08:57._
