### ISSUE TITLE
2.5 release checklist

### ISSUE THREAD

**Issue by bmesuere** [unipept/unipept#458]
- [x] Add planned downtime message to the production website
- [x] Update readme.md
- [x] Put scruffy in production mode and test the production deployment
- [x] Test if font-awesome works
- [x] Test in all browsers
- [x] Create new release, update version numbers and push master
- [x] Add Github release
- [x] apt-get update and upgrade
- [x] update the database
- [x] Deploy production branch to website
- [x] Deploy API branch to API server
- [x] Add 2.5 + changelog news post
- [x] Add tag to google analytics
- [x] Create public branch and push to github.com
- [x] Tweet
- [x] Delete 2.5 feature branches

_[Original issue](https://github.ugent.be/unipept/unipept/issues/458) by @bmesuere on Tue Feb 10 2015 at 09:05._
_Closed by @bmesuere on Wed Feb 25 2015 at 15:04._
