### ISSUE TITLE
3.0 release checklist

### ISSUE THREAD

**Issue by bmesuere** [unipept/unipept#461]
- [x] Copy data dumps
- [x] Load data dumps
- [x] Index data dumps
- [x] Add planned downtime message to the production website
- [x] Release version 1.0.1 of the cli + update version number in Unipept settings
- [x] Update readme.md
- [x] Put nibbler in production mode and test the production deployment
- [x] Test in all browsers
- [x] Create new release, update version numbers and push master
- [x] Add Github release
- [x] apt-get update and upgrade
- [x] update to ruby 2.2.2

```
rvm install 2.2.2
rvm --default use 2.2.2
gem install passenger
passenger-install-apache2-module
```
- [x] Switch databases
- [x] Deploy production branch to website
- [x] Deploy API branch to API server
- [x] Calculate assembly data
- [x] Add 3.0 + changelog news post
- [x] Add tag to google analytics
- [x] Create public branch and push to github.com
- [x] Tweet
- [x] Delete 3.0 feature branches
- [x] Put nibbler back in dev mode

_[Original issue](https://github.ugent.be/unipept/unipept/issues/461) by @bmesuere on Wed Feb 25 2015 at 15:05._
_Closed by @bmesuere on Sat Aug 01 2015 at 13:13._
