### ISSUE TITLE
3.1 release checklist

### ISSUE THREAD

**Issue by bmesuere** [unipept/unipept#541]
- [x] Parse UniProt 2015_12 (9 december)
- [x] Load data on adler
- [x] Calculate the proteome_caches
- [x] Update UniProt version in the Unipept settings file
- [x] Copy data dumps
- [x] Load data dumps
- [x] Index data dumps
- [x] Add planned downtime message to the production website
- [x] Update readme.md
- [x] Put adler in production mode and test the production deployment
- [x] Test in all browsers
- [x] Create new release, update version numbers and push master
- [x] Add Github release
- [x] apt-get update and upgrade
- [x] Switch databases
- [x] Deploy production branch to website
- [x] Deploy API branch to API server
- [x] Add 3.1 + changelog news post
- [x] Add tag to google analytics
- [x] Create public branch and push to github.com
- [x] Tweet
- [x] Delete 3.1 feature branches
- [x] Put adler back in dev mode

_[Original issue](https://github.ugent.be/unipept/unipept/issues/541) by @bmesuere on Sat Dec 05 2015 at 14:36._
_Closed by @bmesuere on Fri Dec 11 2015 at 18:22._

**Comment by bmesuere** [comment]
Checked sample 7 on the 2015_12 release: looks good. As of this release, we don't match S. aureus anymore for sample 7. The only specific peptide that was left in the 2015_11 release is now found in twice the number of proteins including entries from other Staphylococcus species.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/541#issuecomment-22782) by @bmesuere on Fri Dec 11 2015 at 09:53._

**Comment by bmesuere** [comment]
The number of proteomes wen from 10564 to 13248. These are the number for a few key species:

| species | # in UniProt 2015_11 | # in UniProt 2015_12 |
| --- | --: | --: |
| A. Baumannii | 31 | 33 |
| E. Coli | 151 | 349 |
| S. Aureus | 20 | 242 |
| B. Cereus | 107 | 108 |
| L. Lactis | 18 | 18 |


_[Original comment](https://github.ugent.be/unipept/unipept/issues/541#issuecomment-22787) by @bmesuere on Fri Dec 11 2015 at 11:56._
