### ISSUE TITLE
Unipept 3.2 release checklist

### ISSUE THREAD

**Issue by bmesuere** [unipept/unipept#546]
- [ ] Load data on adler
- [ ] Calculate the proteome_caches
- [ ] Update UniProt version in the Unipept settings file
- [ ] Copy data dumps
- [ ] Load data dumps
- [ ] Index data dumps
- [ ] Add planned downtime message to the production website
- [ ] Update readme.md
- [ ] Put adler in production mode and test the production deployment
- [ ] Test in all browsers
- [ ] Create new release, update version numbers and push master
- [ ] Add Github release
- [ ] apt-get update and upgrade
- [ ] Switch databases
- [ ] Deploy production branch to website
- [ ] Deploy API branch to API server
- [ ] Add 3.2 + changelog news post
- [ ] Add tag to google analytics
- [ ] Create public branch and push to github.com
- [ ] Tweet
- [ ] Delete 3.2 feature branches
- [ ] Put adler back in dev mode

_[Original issue](https://github.ugent.be/unipept/unipept/issues/546) by @bmesuere on Fri Dec 11 2015 at 17:16._
