### ISSUE TITLE
4.0 release checklist 

### ISSUE THREAD

**Issue by beardhatcode** [unipept/unipept#647]
- [x] Parse UniProt 2018_06
- [x] Load data on morty
- [x] Calculate the proteome_caches
- [x] Update UniProt version in the Unipept settings file
- [x] Copy data dumps (mount datapapet share)
- [x] Load data dumps  
- [x] Index data dumps
- [ ] ~Add planned downtime message to the production website~
- [x] Update readme.md
- [x] Put morty in production mode and test the production deployment
- [x] Test in all browsers
- [x] Create new release, update version numbers and push master
- [x] Add Github release
- [x] apt-get update and upgrade
- [x] Switch databases
- [x] Deploy production branch to website
- [x] Deploy API branch to API server
- [x] Add 4.0 + changelog news post
- [x] Add tag to google analytics
- [x] Create public branch and push to github.com
- [ ] Tweet
- [x] Delete 4.0 feature branches
- [x] Put morty back in dev mode
 

_[Original issue](https://github.ugent.be/unipept/unipept/issues/647) by @beardhatcode on Tue Aug 14 2018 at 13:56._
_Closed by @beardhatcode on Fri Sep 21 2018 at 14:23._

**Comment by beardhatcode** [comment]
Data is ingeladen en geindexed. 

Nu moet de databank nog geswapped worden en load_proteomes (die van de nieuwe branch die de proteome name niet aanpast) nog gedaan worden. En dan de rest van de checkboxes. (eventueel kan ook de CNAME op morty worden gezet) 

Ik vermoed dat hetzelfde ook op de api server nog niet gebeuren. 

Ik heb al een changelog voor 4.0 geschreven op morty btw. Van een github release had ik hier ook al een Dragt gemaakt. 

_[Original comment](https://github.ugent.be/unipept/unipept/issues/647#issuecomment-78757) by @beardhatcode on Sat Aug 18 2018 at 21:17._

**Comment by beardhatcode** [comment]
@bmesuere can you check the remaining check-boxes?

_[Original comment](https://github.ugent.be/unipept/unipept/issues/647#issuecomment-79015) by @beardhatcode on Fri Aug 31 2018 at 10:40._
